name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    name: runner / Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1

      - name: Build
        run: |
          npm i gitfolio -g
          gitfolio update

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from master,
        # also change the `master` in `refs/heads/master`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: gnztmpz.ovh